-- ============================================================================
-- UniVerse — PostgreSQL schema
-- ============================================================================
-- Generated from backend/src/database/entities.ts (TypeORM 1.x, postgres driver).
--
-- TypeORM mapping used here:
--   @PrimaryGeneratedColumn()      -> integer GENERATED BY DEFAULT AS IDENTITY
--   @Column() (string)             -> varchar
--   @Column({ type: 'text' })      -> text
--   @Column({ type: 'simple-json' })-> text   (TypeORM stores simple-json as text on Postgres)
--   @CreateDateColumn/@UpdateDate  -> timestamp NOT NULL DEFAULT now()
--
-- NOTE: the app boots with synchronize:true by default (DB_SYNCHRONIZE), which
-- creates/updates these tables itself. This file is for provisioning the schema
-- manually (DB_SYNCHRONIZE=false) or for managed providers (Neon, Supabase, RDS).
--
-- Usage:  psql "$DATABASE_URL" -f schema.sql
--
-- Keep this file in sync with entities.ts whenever entity columns change.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Users & roles
-- ---------------------------------------------------------------------------

CREATE TABLE "users" (
  "id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"          varchar NOT NULL DEFAULT '',
  "email"         varchar NOT NULL,
  "passwordHash"  varchar NOT NULL DEFAULT '',
  "role"          varchar NOT NULL DEFAULT 'user',
  "permissions"   text,
  "emailVerified" boolean NOT NULL DEFAULT false,
  "profilePicture" text NOT NULL DEFAULT '',
  "createdAt"     timestamp NOT NULL DEFAULT now(),
  "updatedAt"     timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "IDX_users_email" ON "users" ("email");

CREATE TABLE "roles" (
  "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        varchar NOT NULL,
  "permissions" text,
  "isSystem"    boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX "IDX_roles_name" ON "roles" ("name");

-- ---------------------------------------------------------------------------
-- Content: universities, regions, site settings
-- ---------------------------------------------------------------------------

CREATE TABLE "universities" (
  "id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"                 varchar NOT NULL DEFAULT '',
  "location"             varchar NOT NULL DEFAULT '',
  "province"             varchar NOT NULL DEFAULT '',
  "region"               varchar NOT NULL DEFAULT '',
  "description"          varchar NOT NULL DEFAULT '',
  "image"                varchar NOT NULL DEFAULT '',
  "details"              text,
  "rankings"             text,
  "pros"                 text,
  "cons"                 text,
  "scholarships"         text,
  "applicationDeadlines" text,
  "costOfLiving"         text,
  "visa"                 text,
  "createdBy"            varchar NOT NULL DEFAULT '',
  "updatedBy"            varchar NOT NULL DEFAULT '',
  "createdAt"            timestamp NOT NULL DEFAULT now(),
  "updatedAt"            timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "regions" (
  "id"   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);
CREATE UNIQUE INDEX "IDX_regions_name" ON "regions" ("name");

CREATE TABLE "settings" (
  "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appName"      varchar NOT NULL DEFAULT 'UniVerse',
  "appIcon"      varchar NOT NULL DEFAULT '',
  "address"      varchar NOT NULL DEFAULT '',
  "managerName"  varchar NOT NULL DEFAULT '',
  "contactEmail" varchar NOT NULL DEFAULT '',
  "contactPhone" varchar NOT NULL DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- Audit trail: activity log, version history, trash, bookmarks
-- ---------------------------------------------------------------------------

CREATE TABLE "activity_log" (
  "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action"     varchar NOT NULL DEFAULT '',
  "entity"     varchar NOT NULL DEFAULT '',
  "entityId"   varchar NOT NULL DEFAULT '',
  "entityName" varchar NOT NULL DEFAULT '',
  "actor"      varchar NOT NULL DEFAULT 'admin',
  "meta"       text,
  "timestamp"  timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "versions" (
  "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "universityId" integer NOT NULL,
  "version"      integer NOT NULL DEFAULT 1,
  "snapshot"     text,
  "actor"        varchar NOT NULL DEFAULT 'admin',
  "summary"      varchar NOT NULL DEFAULT '',
  "timestamp"    timestamp NOT NULL DEFAULT now()
);
CREATE INDEX "IDX_versions_universityId" ON "versions" ("universityId");

CREATE TABLE "trash" (
  "id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type"       varchar NOT NULL DEFAULT 'university',
  "item"       text,
  "deletedBy"  varchar NOT NULL DEFAULT 'admin',
  "deletedAt"  timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "bookmarks" (
  "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "universityId"   integer NOT NULL DEFAULT 0,
  "universityName" varchar NOT NULL DEFAULT '',
  "region"         varchar NOT NULL DEFAULT '',
  "action"         varchar NOT NULL DEFAULT 'save',
  "userEmail"      varchar NOT NULL DEFAULT '',
  "timestamp"      timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "reviews" (
  "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "universityId"   integer NOT NULL DEFAULT 0,
  "universityName" varchar NOT NULL DEFAULT '',
  "userEmail"      varchar NOT NULL DEFAULT '',
  "userName"       varchar NOT NULL DEFAULT '',
  "rating"         integer NOT NULL DEFAULT 5,
  "comment"        text NOT NULL DEFAULT '',
  "createdAt"      timestamp NOT NULL DEFAULT now()
);

CREATE TABLE "applications" (
  "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userEmail"      varchar NOT NULL DEFAULT '',
  "universityId"   integer NOT NULL DEFAULT 0,
  "universityName" varchar NOT NULL DEFAULT '',
  "status"         varchar NOT NULL DEFAULT '',
  "notes"          text NOT NULL DEFAULT '',
  "createdAt"      timestamp NOT NULL DEFAULT now(),
  "updatedAt"      timestamp NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- User profile data: preferences, academic scores, AI recommendation results
-- ---------------------------------------------------------------------------

CREATE TABLE "user_preferences" (
  "id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userEmail"           varchar NOT NULL,
  "intendedMajor"       text,
  "degreeLevel"         varchar NOT NULL DEFAULT '',
  "preferredRegions"    text,
  "preferredCountries"  text,
  "budget"              varchar NOT NULL DEFAULT '',
  "gpa"                 varchar NOT NULL DEFAULT '',
  "languageRequirements" text,
  "extracurriculars"    text NOT NULL DEFAULT '',
  "studyMode"           varchar NOT NULL DEFAULT '',
  "startDate"           varchar NOT NULL DEFAULT '',
  "surveyCompleted"     boolean NOT NULL DEFAULT false,
  "updatedAt"           timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX "IDX_user_preferences_userEmail" ON "user_preferences" ("userEmail");

CREATE TABLE "academic_scores" (
  "id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userEmail" varchar NOT NULL,
  "name"      varchar NOT NULL DEFAULT '',
  "score"     text NOT NULL DEFAULT '',
  "scale"     varchar NOT NULL DEFAULT '',
  "status"    varchar NOT NULL DEFAULT '',
  "updatedAt" timestamp NOT NULL DEFAULT now()
);
CREATE INDEX "IDX_academic_scores_userEmail" ON "academic_scores" ("userEmail");

CREATE TABLE "recommendations" (
  "id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userEmail" varchar NOT NULL,
  "source"    varchar NOT NULL DEFAULT 'chat',
  "query"     text NOT NULL DEFAULT '',
  "response"  text NOT NULL DEFAULT '',
  "results"   text,
  "createdAt" timestamp NOT NULL DEFAULT now()
);
CREATE INDEX "IDX_recommendations_userEmail" ON "recommendations" ("userEmail");

-- ---------------------------------------------------------------------------
-- University catalog (normalized views of the university JSON)
-- ---------------------------------------------------------------------------

CREATE TABLE "programs" (
  "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "universityId" integer NOT NULL,
  "name"         varchar NOT NULL DEFAULT '',
  "degreeLevel"  varchar NOT NULL DEFAULT '',
  "description"  text NOT NULL DEFAULT '',
  "updatedAt"    timestamp NOT NULL DEFAULT now()
);
CREATE INDEX "IDX_programs_universityId" ON "programs" ("universityId");

CREATE TABLE "university_requirements" (
  "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "universityId" integer NOT NULL,
  "category"     varchar NOT NULL DEFAULT 'academic',
  "name"         text NOT NULL DEFAULT '',
  "updatedAt"    timestamp NOT NULL DEFAULT now()
);
CREATE INDEX "IDX_university_requirements_universityId" ON "university_requirements" ("universityId");

CREATE TABLE "scholarships" (
  "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "universityId" integer NOT NULL,
  "name"         varchar NOT NULL DEFAULT '',
  "amount"       varchar NOT NULL DEFAULT '',
  "eligibility"  text NOT NULL DEFAULT '',
  "deadline"     varchar NOT NULL DEFAULT '',
  "updatedAt"    timestamp NOT NULL DEFAULT now()
);
CREATE INDEX "IDX_scholarships_universityId" ON "scholarships" ("universityId");
